### ISSUE TITLE
Hashrate compare to a javascript miner?

### ISSUE THREAD

**Issue by emmavray** [mikekazakov/xmr-stak-cpu-ios#2]
This is less if an issue than it is a comment (feel free to delete). I've done a bit of testing and found that my iPhone X will run a hash rate of 10-11H/s using this code.

However - and here's where it gets interesting - running a js miner in a web view produce much higher hash rates of 40-50H/s, on the same device (I used the coinhive miner). I suppose because the Nitro engine optimizes very well - whereas this C++ code is not well optimized at all.

Would be interested to hear your thoughts, but as it stands it seems an interesting insight into how far javascript engines have come.

**Comment by mikekazakov** [comment]
This doesn't look right, A11 should yield about 110H/s.
You should probably check your build configuration and ensure it is set to Release.

**Comment by emmavray** [comment]
That makes a lot more sense, I'll have a look at my configuration.
